### ISSUE TITLE
Win Deployment of VERSION.cmake changes to github.com/seandepagnier/weatherfax_pi

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weatherfax_pi#132]
What follows are references and notes related to deployment appveyor.yml builds

**Conditions:** 
1. Build succeeds
2. Version (major, minor, patch or name_suffix) has been incremented by a change to VERSION.cmake.
3. Description: Somehow allow writing a brief summary description of changes made for Github Description box?  Perhaps use the Pull or Commit titles?

**Result:**
1. Github new release created with the VERSION.cmake information.
2. Github Tag: created is [VERSION]
3. Githhub Name:  The new release name "weatherfax_pi-[VERSION]-win32" and is the same as the file created in appveyor Artifacts TAB minus the ".exe"
4. Github Description:  Allows listing the summary of changes. 

**Appveyor Support Documentation Links:**

- [Publishing artifacts to GitHub Releases](https://www.appveyor.com/docs/deployment/github/) This appears to be the main source of information about pushing the Artifact file to Github Release.
- [Pushing artifacts from scripts](https://www.appveyor.com/docs/packaging-artifacts/#pushing-artifacts-from-scripts)
- [Deploying using Web Deploy](https://www.appveyor.com/docs/deployment/web-deploy/)
- [REST API and Authentication](https://www.appveyor.com/docs/api/#authentication)
- [Getting information about uploaded artifacts](https://www.appveyor.com/docs/packaging-artifacts/#getting-information-about-uploaded-artifacts)
- [Appveyor: Permalink to the last successful build ](https://www.appveyor.com/docs/packaging-artifacts/#permalink-to-the-last-successful-build-artifact)
- [Deploying artifact package as a Windows service](https://www.appveyor.com/docs/deployment/agent/#deploying-artifact-package-as-a-windows-service)
   - <artifact_name>.deploy_service: true
- [Setting up AppVeyor account for GitHub organization](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization)  - At some point it might be needed to setup an Organization account for OpenCPN, but Pavel or Dave would do that.  Various types of users and authorization can be setup so that the various plugins can be handled.
- [Encrypt configuration data](https://ci.appveyor.com/tools/encrypt)  I think I should use this feature for the public key.

**Github Support for Deployment**  REST API v3

- [Github Support for Delivering Deployments](https://developer.github.com/v3/guides/delivering-deployments/)   This is more involved than I intend to get, but it allows some automation and also a list of choices for what is to happen.  Good information

**Comment by rgleason** [comment]
With these Deploy Settings at the end of Appveyor.yml

> deploy:
>   description: 'release created by AppVeyor CI'
>   provider: GitHub
>   auth_token: '%GitHub_auth_token%'
>   artifact: installer
>   draft: true
>   prerelease: true
>   on:
>     appveyor_repo_tag: true # deploy on tag push only
> configuration: Release  # Debug contains non-redist MS DLLs
> 

My fork gets this error and does not deploy the Artifact file to a Github Release

> "Uploading artifacts...
> [1/1] build\weatherfax_pi-1.9.001-ov42-win32.exe (721,836 bytes)...100%
> "GitHub" deployment has been skipped as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
> Build success"
> 

The reason it is failing is because I have not inserted my token into 
>   auth_token: '%GitHub_auth_token%'

**Comment by rgleason** [comment]
Trying github  [Deploy keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) for my Weatherfax_pi repository

**Comment by rgleason** [comment]
[Unable to deploy Artifact](https://stackoverflow.com/questions/48359909/unable-to-deploy-artifact-from-appveyor-to-github)

**Comment by rgleason** [comment]
These two links helped explain how it works.

[Build on tags (GitHub, GitLab and BitBucket only) - also deploy](https://www.appveyor.com/docs/branches/#build-on-tags-github-gitlab-and-bitbucket-only)

[Publishing artifacts to GitHub Releases - Usage Scenario - Release every tag build](https://www.appveyor.com/docs/deployment/github/#usage-scenarios) 

Then after you've done all your commits and pushed to the remote origin, wait for appveyor to complete properly. Then simply push a new tag to the the remote.  Then Appveyor will webhooks will notice this and start appveyor build again.

To push a tag (done after a commit).
When on the branch and commit you want...
Examples

- git tag v1.9.2-ov42
- git push origin tag v1.9.2-ov42       to push the tag to remote 'origin'.
- git tag -d v1.9.2-ov2         to delete the local tag
- git push origin --delete <tagname>  to delete the remote tag
 
This is the bottom portion of the appveyor file so far.  The auth_token is not working properly yet, but I believe Deployment to github release is likely working.


```
(top of file is missing for environment, scripts, install and build)

# Artifacts Configuration    #
artifacts: # push all files in directory
  - path: build\weatherfax_pi*.exe
    name: installer

# Deploy Configuration to GitHub Releases
deploy:
  release: weatherfax_pi- $(APPVEYOR_REPO_TAG_NAME)-win32
  description: 'Release of weatherfax_pi $(APPVEYOR_REPO_TAG_NAME) tag created by AppVeyor build $(appveyor_build_version)'
  provider: GitHub
  auth_token:
   secure:8Vd+PKGvcGO8YecwHIpgv6zuSaijeH3fLNUD99GcaJnjNQIluOlkOqB+ifLXCXSD
  # Encrypted fingerprint
  artifact: installer, portable
  draft: true
  prerelease: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: true   # deploy on tag push only
    configuration: Release    # Debug contains non-redist MS DLLs
#   branch: master   # release from master branch only
```

Next issue to work out is authentication.
