### ISSUE TITLE
Use of appveyor 'auth_token' to push a new github release

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/weatherfax_pi#134]
I've been getting this result:
```
Collecting artifacts...
Found artifact 'build\weatherfax_pi-1.9.002-ov42-win32.exe' matching 'build\weatherfax_pi*.exe' path
Uploading artifacts...
[1/1] build\weatherfax_pi-1.9.002-ov42-win32.exe (721,850 bytes)...100%
Deploying using GitHub provider
Creating "weatherfax_pi-'v1.9.2-ov42'-win32" release for repository "rgleason/weatherfax_pi" tag "v1.9.2-ov42" commit "c393a31c6d2b6c673aa4d2fd97aa89583821ae18".
..Error creating GitHub release: 
Error reading repository 'rgleason/weatherfax_pi' releases: 401 - Unauthorized
```
It is obvious now that authorization keys are not set up correctly. 
[Pushing to remote Git repository from a build](https://www.appveyor.com/docs/how-to/git-push/)

Also useful [Publishing to github releases - Provider settings ](https://www.appveyor.com/docs/deployment/github/#provider-settings)

> GitHub authentication token (auth_token) - OAuth token used for authentication against GitHub API. You can generate Personal API access token at https://github.com/settings/tokens. Minimal token scope is repo or public_repo to release on private or public repositories respectively. Be sure to encrypt your token using “Encrypt configuration data” page in AppVeyor (Settings → Encrypt YAML).  - I thought I had done this, but I misunderstood something.

Under  my github account  user > settings > developer (at the bottom) there are 3 selections
- Oauth Apps  - nothing entered
- Github Apps - nothing entered
- Personal Tokens  (I have 4 tokens registered there for different machines, these can be edited for various capabilities.)

Some notes from a user:
> In order for appveyor to upload to Github releases you have to generate a token on github and give it to appveyor.   Instructions here "GitHub authentication token" - https://www.appveyor.com/docs/deployment/github
cache:
  - C:\Users\appveyor\.m2

Bottom of the users appveyor, similar to mine.

```
deploy:
  - provider: GitHub
    auth_token:
      secure: Hq5VDnfPj9yDRim502Eyhn7rFSgjfo3TiRs2xM+qP/wm/Wav6q/XeVNIGEEdXbtN
    artifact: mavgclinstaller
    draft: false
    prerelease: false
    on:
appveyor_repo_tag: true 
```
